### ISSUE TITLE
Embedd in Python Code

### ISSUE THREAD

**Issue by DeastinY** [kootenpv/whereami#15]
Hi,
I did not find any documentation on using this module from other Python code. When importing it does not expose any functionality. Would it be possible to allow other modules to work with `whereami` ?

**Comment by kootenpv** [comment]
You'd have to dig into the code as I have indeed not provided ways for people to use it. But you can use this should be the starting point: https://github.com/kootenpv/whereami/tree/master/whereami

For example, you can do something like this:

from whereami.predict import predict
predict()   # equal to the CLI version of predict

The components are in there, but you'll have to nagivate yourself.

**Comment by kootenpv** [comment]
Ugh, it is so sad that your changes to your fork did not make it upstream :( All you would have had to do was a PR? I'm sad I didn't notice it.

I now updated it in the latest version.
