### ISSUE TITLE
nonfunctional due to alternative wifi device name

### ISSUE THREAD

**Issue by Cerv4ntez** [kootenpv/whereami#37]
Hi,

i'm trying to get whereami working on ubuntu zesty, the current package version is 0.34

out of the box, there is no real functionality, whereami appears to take whatever argument i feed it as a location e.g. 
_~#whereami locations
Moving from home to locations_

Since i also get "eth0: Error while getting interface flags: no such device"

i think the problem might be that #1 since i have a loptop without a network port there is no eth0 and #2 since my wifi device is called wlp2s0 instead of wlan0 whereami does not know where to look for an environmen.

Some indication from the application that its not seeing any network would be nice, also some guidance on how to change the network device name correctly would be great

**Comment by kootenpv** [comment]
This was not complicated but still a little bit of work :)

kootenpv/access_points had to be upgraded.

So you need to do a proper upgrade with `pip install -U --no-cache whereami`.

```
pascal@MBP:~/egoroot/whereami $ access_points -v
access_points version: [0.4.56], Python 3.5.0
major version: 0  (breaking changes)
minor version: 4  (extra feature)
micro version: 56 (commit count)
Find out the most recent version at https://github.com/kootenpv/access_points
pascal@MBP:~/egoroot/whereami $ whereami -v
whereami version: [0.4.68], Python 3.5.0
Major version: 0  (breaking changes)
Minor version: 4  (extra feature)
Micro version: 68 (commit count)
Find out the most recent version at https://github.com/kootenpv/whereami
```

Could you let me know if it works for you?

    whereami learn --location here --device wlp2s0

**Comment by Cerv4ntez** [comment]
Your solution works, thank you. i did uninstall whereami with apt and install it with pip as you suggested though. The ubuntu supplied version stays defunct(which is not your problem of course).

 

i now see expected output, will look at configuring it in the coming days!

 

Gesendet: Sonntag, 23. April 2017 um 16:44 Uhr
Von: "Pascal van Kooten" <notifications@github.com>
An: kootenpv/whereami <whereami@noreply.github.com>
Cc: Cerv4ntez <WIRED79@gmx.at>, Author <author@noreply.github.com>
Betreff: Re: [kootenpv/whereami] nonfunctional due to alternative wifi device name (#37)


This was not complicated but still a little bit of work :)

kootenpv/access_points had to be upgraded.

So you need to do a proper upgrade with pip install -U --no-cache whereami.

pascal@MBP:~/egoroot/whereami $ access_points -v
access_points version: [0.4.56], Python 3.5.0
major version: 0  (breaking changes)
minor version: 4  (extra feature)
micro version: 56 (commit count)
Find out the most recent version at https://github.com/kootenpv/access_points
pascal@MBP:~/egoroot/whereami $ whereami -v
whereami version: [0.4.68], Python 3.5.0
Major version: 0  (breaking changes)
Minor version: 4  (extra feature)
Micro version: 68 (commit count)
Find out the most recent version at https://github.com/kootenpv/whereami


Could you let me know if it works for you?

whereami learn --location here --device wlp2s0
