### ISSUE TITLE
Locations lose trailing 't' or 'x'

### ISSUE THREAD

**Issue by iamthad** [kootenpv/whereami#51]
The names of locations lose any number of trailing 't' or 'x' characters, e.g.

```console
$ whereami learn -l couch-right &>/dev/null
$ whereami locations
couch-righ: 1
```

This is due to using `rstrip(".txt")` on the filename at [get_data.py:42](https://github.com/kootenpv/whereami/blob/master/whereami/get_data.py#L42), which will strip any number of '.', 't', or 'x' characters.

**Comment by cherrynoize** [comment]
This is still an issue.
