### ISSUE TITLE
How can I track my phone?

### ISSUE THREAD

**Issue by iudeen** [kootenpv/whereami#53]
I would like to track my phone, to get its location and obtain RSSI values as well. How can it be done? Any ideas?

**Comment by kootenpv** [comment]
Have a look here: https://github.com/schollz/find3

**Comment by iudeen** [comment]
@kootenpv I did. It seems like they have used Go, and moreover the server is down there. This one is much simpler, so I thought of using this one...I just need a heads-up on where to start to track my phone accurately

**Comment by kootenpv** [comment]
There's no implementation for android of this and it will not be logical to do that based on this code.

I guess you are thinking to capture the android data and then just use whereami for the model/prediction? The issue would still be if you want to actually use it on the phone.

I think FIND is your best option.

**Comment by iudeen** [comment]
Yes, all I want is to track my phone using available Access point information (RSSI). It should happen even if I am not connected to some of the access points.

**Comment by kootenpv** [comment]
Yea, for using whereami you don't need to be connected to an access point.
Do note that if you want to share your phone's location you obviously will need to have a working internet connection (though 3g/4g can work).

You can make a simple server around whereami which would accept data.

But the main problem remains... getting the RSSI data on android.

**Comment by iudeen** [comment]
Thanks for your replies. 

Yes, I am trying to create an app that would obtain RSSI values.

Considering, it can get me a list of RSSI values, is there any possibility of using whereami's machine learning logic to estimate the location?

If that's possible, it would be great. If not, I should try to recreate the logic and try to fit in.

**Comment by MatthewScholefield** [comment]
Just a heads up, while the results I believe are slightly cached, [Termux support for Android](https://github.com/kootenpv/access_points/pull/15) has been merged into `access_points`, the tool used for scanning networks. So, theoretically, this now should work.

**Comment by peter-dolkens** [comment]
@kootenpv - [monitor.sh](https://github.com/andrewjfreyer/monitor) aims to do that without the machine learning.

Pay attention to the open PRs, there's a few bug fixes there.
