### ISSUE TITLE
Does deleting {{location}}.txt files affect the model?

### ISSUE THREAD

**Issue by markovchainz** [kootenpv/whereami#54]
I am trying to delete a single location... I deleted its relevant .txt file but running a prediction still shows the model predicting I am in that location. 

Am I doing something wrong or should I take a different approach to deleting a location? (Assuming it is possible within the current library).

Thanks for any help!!

**Comment by kootenpv** [comment]
Only when you add a new sample will the model be retrained. So you could just add an extra sample for a location and it should be fixed
