### ISSUE TITLE
whereami rename old_label new_label not working

### ISSUE THREAD

**Issue by gseiki** [kootenpv/whereami#55]
If I run the following command "whereami rename old_label new_label" terminal outputs "whereami: error: unrecognized arguments: old_label new_label". Any advice for me? 

I'm running: 
OSX High Sierra
Python3.8.6
PIP3
whereami version 0.4.85

**Comment by kootenpv** [comment]
Try 

    whereami rename --label a --new_label b

**Comment by gseiki** [comment]
Thanks! That did the trick.
