### ISSUE TITLE
Support for different floors, aka 3D triangulation.

### ISSUE THREAD

**Issue by Supermagnum** [kootenpv/whereami#59]
Hello, assume that a two story square shaped  house has eight rooms:
First floor: kitchen, living room,guest room, bathroom 1
Second floor: master bedroom, bathroom 2,kid room1, office.

Each rooms outermost corner ( away from the houses center) has a raspberry pi that listens to the WiFi. 

It should then be possible to triangulate in 3D.

**Comment by kootenpv** [comment]
Signal strength is much worse over floors, so in a way it supports 3d out of the box. As long as you have multiple wifi access points. The methodology here has nothing to do with "multiple devices listening to wifi"
