### ISSUE TITLE
Issue with "whereami predict | say"

### ISSUE THREAD

**Issue by wdibi** [kootenpv/whereami#6]
When I run, "whereami predict_proba" I get a value of 1.0 for my location. But when I do "whereami predict | say" it does nothing.

**Comment by wdibi** [comment]
<img width="567" alt="screen shot 2016-09-28 at 10 28 18 am" src="https://cloud.githubusercontent.com/assets/12821603/18898818/b3c6d2e8-8566-11e6-82e7-9bffed8f408d.png">

**Comment by kootenpv** [comment]
And what does just `whereami predict` do?

**Comment by wdibi** [comment]
That works, thank u=you

**Comment by kootenpv** [comment]
The "say" command actually says the class out loud (thus if your sound is off, you won't hear anything) :)

**Comment by wdibi** [comment]
I didn't know that. Thanks for clarifying!!
