### ISSUE TITLE
Windows 10: ValueError: Found array with 0 feature(s) (shape=(100, 0)) while a minimum of 1 is required.

### ISSUE THREAD

**Issue by balta2ar** [kootenpv/whereami#7]
I'm using miniconda.

```
(py2) C:\Users\jane_>python --version
Python 2.7.12 :: Continuum Analytics, Inc.
```

```
(py2) C:\Users\jane_>conda list
# packages in environment at C:\Users\jane_\Miniconda3\envs\py2:
#
access-points             0.0.18                    <pip>
mkl                       11.3.3                        1
numpy                     1.11.1                   py27_1
pip                       8.1.2                    py27_0
python                    2.7.12                        0
scikit-learn              0.17.1              np111py27_1
scipy                     0.18.1              np111py27_0
setuptools                27.2.0                   py27_1
tqdm                      4.8.4                     <pip>
vs2008_runtime            9.00.30729.1                  2
wheel                     0.29.0                   py27_0
whereami                  0.2.29                    <pip>
```

```
(py2) C:\Users\jane_>whereami learn -l bookshelf -n 100
100%|################################################################################| 100/100 [00:14<00:00,  6.79it/s]
Traceback (most recent call last):
  File "c:\users\jane_\miniconda3\envs\py2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\jane_\miniconda3\envs\py2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\jane_\Miniconda3\envs\py2\Scripts\whereami.exe\__main__.py", line 9, in <module>
  File "c:\users\jane_\miniconda3\envs\py2\lib\site-packages\whereami\__main__.py", line 34, in main
    learn(args.location, args.num_samples)
  File "c:\users\jane_\miniconda3\envs\py2\lib\site-packages\whereami\learn.py", line 25, in learn
    train_model()
  File "c:\users\jane_\miniconda3\envs\py2\lib\site-packages\whereami\pipeline.py", line 33, in train_model
    lp.fit(X, y)
  File "c:\users\jane_\miniconda3\envs\py2\lib\site-packages\sklearn\pipeline.py", line 165, in fit
    self.steps[-1][-1].fit(Xt, y, **fit_params)
  File "c:\users\jane_\miniconda3\envs\py2\lib\site-packages\sklearn\ensemble\forest.py", line 212, in fit
    X = check_array(X, dtype=DTYPE, accept_sparse="csc")
  File "c:\users\jane_\miniconda3\envs\py2\lib\site-packages\sklearn\utils\validation.py", line 415, in check_array
    context))
ValueError: Found array with 0 feature(s) (shape=(100, 0)) while a minimum of 1 is required.
```

**Comment by balta2ar** [comment]
```
(py2) C:\Users\jane_>access_points
[]
```

**Comment by balta2ar** [comment]
The result is the same if I run command prompt as Administrator:
```
(py2) C:\Windows\system32>access_points
[]
```

**Comment by kootenpv** [comment]
Could you try in a clean shell `netsh wlan show networks mode=bssid` and see if that yields anything?

**Comment by balta2ar** [comment]
```
C:\Users\jane_>netsh wlan show networks mode=bssid

Interface name : Wi-Fi
There are 1 networks currently visible.

SSID 1 : 3.14159265359
    Network type            : Infrastructure
    Authentication          : WPA2-Personal
    Encryption              : CCMP
```

**Comment by kootenpv** [comment]
I have no idea what is going on. Perhaps other windows users have more ideas.

**Comment by balta2ar** [comment]
Turning WiFi off and on again helps.

However, `crossval` command hangs (I'm not sure how long it takes), and here is what it prints if I Ctrl-C:
```
(py2) C:\Users\jane_>whereami crossval
forrtl: error (200): program aborting due to control-C event
Image              PC                Routine            Line        Source
libifcoremd.dll    00007FFE3D8643E4  Unknown               Unknown  Unknown
KERNELBASE.dll     00007FFE64095674  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFE66B02D92  Unknown               Unknown  Unknown
ntdll.dll          00007FFE66BB9F64  Unknown               Unknown  Unknown
```

On the other hand, predict_proba shows this no matter where in the flat I stand:
```
(py2) C:\Users\jane_>whereami predict_proba
{'bookshelf': 0.50329566888406263, 'kitchen': 0.49670433111593731}
```

I only move about ~5 meters but I still expect at least slightly different numbers...

**Comment by kootenpv** [comment]
Perhaps could you try to take more samples and see if you can get the output to change? 5 meters should indeed change the numbers a bit I would say.

**Comment by kootenpv** [comment]
Please try it once more, I think there won't be any more errors as of `whereami==0.3.37`. You might want to remove first the ~/.whereami folder (or if you care for the data, just delete the model)

**Comment by kootenpv** [comment]
@balta2ar Wondering if it works for you?

**Comment by balta2ar** [comment]
@kootenpv Sorry for delaying response, I'll try to check it again soon and reply here! Thanks!

**Comment by kootenpv** [comment]
@balta2ar very curious, do let me know :)

**Comment by balta2ar** [comment]
Ok, I've tried the latest version yesterday but in a different environment: I installed Ubuntu 16.04.1 on my notebook. As it can be seen, the output is changing:
```
nst@unicorn:~$ source activate py3k
(py3k) nst@unicorn:~$ whereami predict_proba
{'kitchen': 0.76000000000000001, 'sofa': 0.23999999999999999}
(py3k) nst@unicorn:~$ whereami predict_proba
{'sofa': 0.23999999999999999, 'kitchen': 0.76000000000000001}
(py3k) nst@unicorn:~$ whereami predict_proba
{'kitchen': 0.0, 'sofa': 1.0}
(py3k) nst@unicorn:~$ whereami predict_proba
{'sofa': 1.0, 'kitchen': 0.0}
(py3k) nst@unicorn:~$ whereami predict_proba
{'kitchen': 0.0, 'sofa': 1.0}
(py3k) nst@unicorn:~$ whereami predict_proba
{'sofa': 0.47199999999999998, 'kitchen': 0.52800000000000002}
(py3k) nst@unicorn:~$ whereami predict_proba
{'sofa': 0.23999999999999999, 'kitchen': 0.76000000000000001}
(py3k) nst@unicorn:~$ whereami predict_proba
{'sofa': 0.23999999999999999, 'kitchen': 0.76000000000000001}
(py3k) nst@unicorn:~$ whereami predict_proba
{'sofa': 0.36199999999999999, 'kitchen': 0.63800000000000001}
(py3k) nst@unicorn:~$ whereami predict_proba
{'sofa': 0.36199999999999999, 'kitchen': 0.63800000000000001}
(py3k) nst@unicorn:~$ whereami predict_proba
{'kitchen': 0.63800000000000001, 'sofa': 0.36199999999999999}
(py3k) nst@unicorn:~$ whereami predict_proba
{'kitchen': 0.63800000000000001, 'sofa': 0.36199999999999999}
(py3k) nst@unicorn:~$ whereami predict_proba
{'kitchen': 0.63800000000000001, 'sofa': 0.36199999999999999}
(py3k) nst@unicorn:~$ whereami predict_proba
{'kitchen': 0.63800000000000001, 'sofa': 0.36199999999999999}
(py3k) nst@unicorn:~$ whereami predict_proba
{'sofa': 0.36199999999999999, 'kitchen': 0.63800000000000001}
(py3k) nst@unicorn:~$ whereami predict_proba
{'sofa': 1.0, 'kitchen': 0.0}
(py3k) nst@unicorn:~$
```

I think I can run it again on Windows, if you're curious, but I expect more or less the same output because it's bound to be imprecise due to my hardware, I believe.

**Comment by kootenpv** [comment]
How much distance is there? How many samples did you take for learning? Were you at the same spot when you did predict_proba? What is the output of `access_points -n`?

**Comment by balta2ar** [comment]
> How much distance is there?

Up to ~5-7 meters.

> How many samples did you take for learning?

100 as suggested in the README.

> Were you at the same spot when you did predict_proba?

No, I was moving across the flat (mostly along the path from sofa to kitchen) and I was running predict_proba at different spots.

```
(py3k) nst@unicorn:~$ access_points -n
15
```

**Comment by kootenpv** [comment]
If you were indeed moving, that shows it works? It shows the probability it thinks you are in a certain location. That will vary when you move, and it will just vary "over time" as wifi signal tends to vary from time to time. But in general, it should still make a good prediction.
Do you think the predictions are not good when you are on the sofa :-)?

**Comment by balta2ar** [comment]
> If you were indeed moving, that shows it works?

Yes, sure! When I moved from sofa to kitchen it properly changed the output of prodict_proba. Unfortunately, I suspect WiFi measurements of my hardware are too coarse to see any significant changes when I do a single step or two. To see the changes I had to go to another room.

> Do you think the predictions are not good when you are on the sofa :-)?

Well, technically, predictions were right. However I wonder why there is more confidence when I'm on the sofa, than when I'm in the kitchen? Though I can answer my own question: thrash data in input, thrash result in the output, no magic here :)

What's your experience with that? Is one step enough for your WiFi hardware to detect it?

**Comment by kootenpv** [comment]
It depends on objects, but you should otherwise expect that in the middle, you'd roughly have 50% (too much variation for that to be close to exact).

Taking more samples at different times will also improve predictions.

One step is quite small, I think I have 70% accuracy for detecting a difference of 2 meters (couch A to couch B). Room to room is usually close to 100%

**Comment by kootenpv** [comment]
I'm going to make a jump to the conclusion that this has been solved after taking more samples :-) 
Feel free to reopen.
