### ISSUE TITLE
[Python2] FileNotFoundError is not defined

### ISSUE THREAD

**Issue by rfilmyer** [kootenpv/whereami#9]
[There are no FileNotFoundErrors in Python 2.7, only IOErrors](http://stackoverflow.com/questions/21367320/searching-for-equivalent-of-filenotfounderror-in-python-2)

**Comment by kootenpv** [comment]
Thanks, I updated it. The message you would have seen would be the following: First learn a location, e.g. with `metadate learn -l kitchen`.

**Comment by kootenpv** [comment]
Should be solved.
